name: Django CI/CD
on:
  push:
    branches: ["feature/cicd"]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      EMAIL_BACKEND: ${{ secrets.EMAIL_BACKEND }}
      EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
      EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
      EMAIL_USE_TLS: ${{ secrets.EMAIL_USE_TLS }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        run: pip install --user uv

      - name: Install dependencies with uv
        run: ~/.local/bin/uv sync

      - name: Wait for DB
        run: |
          if [ -n "${{ env.DB_HOST }}" ] && [ "${{ env.DB_HOST }}" != "localhost" ]; then
            echo "Waiting for DB at $DB_HOST:$DB_PORT"
            for i in {1..30}; do
              nc -z $DB_HOST $DB_PORT && { echo "DB reachable"; break; }
              echo "DB not ready yet... ($i/30)"; sleep 2
            done
          fi

      - name: Run migrations
        run: ~/.local/bin/uv run python manage.py migrate --noinput

      - name: Run tests
        run: ~/.local/bin/uv run pytest -v

  trivy-sast:
    name: Run Trivy Static Code Scan
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'

  deploy:
    needs: [test, trivy-sast]  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /var/www/edulance
            git fetch origin feature/cicd
            git reset --hard origin/feature/cicd
            ~/.local/bin/uv sync
            ~/.local/bin/uv run python manage.py migrate --noinput
            ~/.local/bin/uv run python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
